ALTER TABLE repository_connections ADD COLUMN IF NOT EXISTS can_read BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE repository_connections ADD COLUMN IF NOT EXISTS can_write BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE repository_connections ADD COLUMN IF NOT EXISTS can_manage BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE repository_connections ADD COLUMN IF NOT EXISTS provider_permission VARCHAR(64);
